### ISSUE TITLE
import error for turtle

### ISSUE THREAD

**Issue by brewchetta** [learn-co-curriculum/python-p3-oop-putting-it-all-together#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195257?module_item_id=439030

### Concern

Unclear why we need the turtle library imported for this lab. When I run pytest, the shoe_test.py file errors out and can't seem to get tkinter (not sure how I have turtle but not the dependencies it needs so that's a big question mark).

### Suggested Changes

Remove the import turtle line from shoe_test.py and it ran smoothly for me!

**Comment by professor-ben** [comment]
I think this was VSCode autocomplete shenanigans. Thanks for reporting.
