### ISSUE TITLE
Lab too easy?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-oop-putting-it-all-together#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195257?module_item_id=439030

### Concern

We can basically pass all the tests to this lab by give `Book` and `Shoe` an `__init__` method and a `turn_page` and `cobble` method, respectively. Once we have these set up, all the other tests automatically pass, since python allows you to assign attributes freely. If this is meant to illustrate the ease of OOP with Python, then it's great. 

But, this could also be an opportunity for students to practice using properties more. We don't have to make all attributes properties, but at least making a few of them properties could be good practice. It could also highlight the difference between non-properties, whose tests would pass as soon as the class is set up, and properties, which would need to meet certain requirements. Thoughts?

**Comment by professor-ben** [comment]
My original intention _was_ to show how nice it was to freely add to existing objects, but I agree that this isn't the most exciting way to show it. I will get back to this later in our QA cycle.

**Comment by professor-ben** [comment]
This is updated now to include properties for shoe and book. Thanks for raising this issue.

All the best,
Ben

**Comment by Matt-Eva** [comment]
Of course, thanks Ben!
