### ISSUE TITLE
Putting It All Together Feedback

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-oop-putting-it-all-together#5]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195257?module_item_id=439030

### Concern

- “Putting It All Together: Object-Oriented Programming Lab” –” Shoe in shoe.py says that the shoe has been repaired.” test is unclear. Doesn’t tell you what name or what to return. Unsure if this is intentional.
- “Putting It All Together: Object-Oriented Programming Lab” – most the tests you need to write no code.
- “Use the property() function to create properties and validate input.” This is never needed to pass the tests.

**Comment by professor-ben** [comment]
This is updated now to include properties for shoe and book. Thanks for raising this issue.

All the best,
Ben
