### ISSUE TITLE
Module Not Found by Tests

### ISSUE THREAD

**Issue by a-JAVA-chip-frappuccino** [learn-co-curriculum/python-p3-oop-putting-it-all-together#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195257?module_item_id=439030

### Concern

The tests don't work as they do not recognize that the class containing the student's code is accessible by the testing files.

### Additional Context

____________________________ ERROR collecting testing/shoe_test.py _____________________________
ImportError while importing test module '/Users/eleanorkelman/Documents/Python Phase 3 Labs/python-p3-oop-putting-it-all-together/lib/testing/shoe_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testing/shoe_test.py:3: in <module>
    from shoe import Shoe
E   ModuleNotFoundError: No module named 'shoe'

**Comment by professor-ben** [comment]
This should be fixed with the updates to the Pipfile and pytest structure. Please verify if you have a second and I will re-open if it's still an issue.

Thanks,
Ben
